[project]
name = "recent-successful-operations"
version = "0.1.0"
description = "Виджет, который показывает несколько последних успешных банковских операций клиента."
authors = [
    {name = "Viktor Smirnov",email = "tin.r@mail.ru"}
]
requires-python = "^3.13"
dependencies = [
    "requests (>=2.34.2,<3.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "pandas (>=3.0.5,<4.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)",
    "pandas-stubs (>=3.0.5.260730,<4.0.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
lint = [
    "flake8 (>=7.3.0,<8.0.0)",
    "black (>=26.5.1,<27.0.0)",
    "isort (>=8.0.1,<9.0.0)",
    "mypy (>=2.1.0,<3.0.0)"
]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)"
]

[tool.black]
line-length = 119
exclude = '''
(
  /(
      \.idea
    | \.mypy_cache
  )/
)
'''

[tool.isort]
line_length = 119
skip = [".idea",".mypy_cache"]

[tool.mypy]
disallow_untyped_defs = true
warn_return_any = true
exclude = '.idea, .mypy_cache'